# Title of the document
title: "NLP Model Test Report"

rai_cache_path: "~/.cache/rai"

checklist:
  run: True
  tests:
    in sample correctness:
      type: "MFT"
      capability: "Correctness"
      description: "testing samples in train/test data"
      num_sentences: 10
      perturb:
      template:

    adding thank-you:
      type: "INV"
      capability: "Robustness"
      description: "adding thank-yous to end of sentence"
      num_sentences: 10
      perturb:
        change: "append_to_end"
        phrases:
          - " Thank you."
          - " Best regards,"
          - " thank u."
      template:

    adding typos:
      type: "INV"
      capability: "Robustness"
      description: "adding_typos"
      num_sentences: 10
      perturb:
        change: "adding_typos"
        phrases:
      template:

textattack:
  run: True
  recipe: "TextFoolerJin2019"
  embedding: "paragramcf"
  customized_embedding:

