from .html import HTMLHTML
from .container import HTMLContainer
from .table import HTMLTable
from .root import HTMLRoot
from .sentence_pair import HTMLSentencePair
from .togglerow import HTMLToggleRow
from .toggletable import HTMLToggleTable
from .cltest import HTMLCLTest
from .togglebutton import HTMLToggleButton
from .collapse import HTMLCollapse
from .ta import HTMLTA
